### ISSUE TITLE
Allocator wrestling

### ISSUE THREAD

**Issue by beyang** [sourcegraph/gophercon-2018-liveblog#11]
Seebs is working on one too I believe but will keep this around as a backup.

**Comment by ryan-blunden** [comment]
Thanks! Posting this now,.

**Comment by ryan-blunden** [comment]
Going with this as I haven't heard from Seebs.

**Comment by ryan-blunden** [comment]
It's now live.

Tweet: https://twitter.com/srcgraph/status/1034562181809881088
Blog: https://about.sourcegraph.com/go/gophercon-2018-allocator-wrestling
